name: flutter_zalopay_sdk
description: A plugin for ZaloPay App To App Purchase. This plugin allows you to open ZaloPay app and receive status of the order, then back to your app. Supports iOS and Android.
version: 0.1.13
authors:
  - Son Vo <ngocson160391@gmail.com>
  - Ha Tran <tranvietha.2809@gmail.com>
  - Bao Nguyen <nguyennhubao999@gmail.com>
homepage: https://github.com/sonvp/flutter_zalo

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.flutterzalopay.flutter_zalo_sdk
        pluginClass: FlutterZaloSdkPlugin
      ios:
        pluginClass: FlutterZaloSdkPlugin
